name: Release Snaps

on:
  pull_request:
    types:
      # - closed
      - synchronize

jobs:
  get-snap-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.parse-labels.outputs.branches }}
    steps:
      - name: Parse labels
        id: parse-labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
          BASE: ${{ github.event.pull_request.base.ref }}

        run: |
          # Appends '/$BASE' to the PR labels that start with 'snap/' and filters out everything else, including 'snap/none'
          # Example: ['mylabel', 'snap/none', 'snap/ubuntu-desktop-bootstrap'] -> ['snap/ubuntu-desktop-bootstrap/main']
          BRANCHES=$(echo $LABELS | jq -c "[.[]|select(.!=\"snap/none\")|select(startswith(\"snap/\"))|.+\"/$BASE\"]")
          echo "Found branches: $BRANCHES" >> $GITHUB_STEP_SUMMARY
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

  release-snaps:
    runs-on: ubuntu-latest
    needs: get-snap-branches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get-snap-branches.outputs.branches) }}

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Bump source-commit in snapcraft.yaml
        env:
          BRANCH: ${{ matrix.branch }}
        run: |
          case $BRANCH in
            snap/ubuntu-desktop-bootstrap/*)
              PART_NAME='ubuntu-bootstrap'
              ;;
            snap/ubuntu-desktop-init/*)
              PART_NAME='ubuntu-desktop-init'
              ;;
            snap/factory-reset-tools/*)
              PART_NAME='factory-reset-tools'
              ;;
            *)
              echo "::error::Unknown branch '$BRANCH'"
              exit 1
          esac

          OLD_HASH=$(yq ".parts[\"$PART_NAME\"][\"source-commit\"]" snap/snapcraft.yaml)
          sed -i "s/$OLD_HASH/<new hash>/" snap/snapcraft.yaml
          cat snap/snapcraft.yaml

      - name: Open PRs on release branches
        run: git diff
